

INSERT INTO PAIS (ID_PAIS, NOMBRE_PAIS, ESTADO_PAIS) VALUES ('COL', 'Colombia', 'A');


INSERT INTO DEPARTAMENTO (ID_DPTO, NOMBRE_DPTO, ID_PAIS_DPTO) VALUES ('25', 'Cundinamarca', 'COL');
INSERT INTO DEPARTAMENTO (ID_DPTO, NOMBRE_DPTO, ID_PAIS_DPTO) VALUES ('11', 'Bogotá D.C.', 'COL');


INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_DPTO_CIUDAD) VALUES ('11.001', 'Bogotá', '11');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_DPTO_CIUDAD) VALUES ('25.126', 'Cajicá', '25');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_DPTO_CIUDAD) VALUES ('25.214', 'Cota', '25');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_DPTO_CIUDAD) VALUES ('25.286', 'Funza', '25');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_DPTO_CIUDAD) VALUES ('25.377', 'La Calera', '25');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_DPTO_CIUDAD) VALUES ('25.43', 'Madrid', '25');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_DPTO_CIUDAD) VALUES ('25.473', 'Mosquera', '25');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_DPTO_CIUDAD) VALUES ('25.754', 'Soacha', '25');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_DPTO_CIUDAD) VALUES ('25.785', 'Tabio', '25');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_DPTO_CIUDAD) VALUES ('25.799', 'Tenjo', '25');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_DPTO_CIUDAD) VALUES ('25.899', 'Zipaquirá', '25');


INSERT INTO TIPOMOV (ID_TIPOMOV, NOM_TIPOMOV) VALUES 
(1, 'Entrada por Ajuste'),
(2, 'Salida por Ajuste'),
(3, 'Ventas Crédito'),
(4, 'Ventas Contado'),
(5, 'Cambio de sede'),
(6, 'Ingreso por Garantía'),
(7, 'Salida por Garantía'),
(8, 'Ingreso por Reparación'),
(9, 'Salida por Reparación');


INSERT INTO TIPODOCUMENTO (ID_TIPODOCUMENTO, DESCRIPCION_TIPODOCUMENTO, ESTADO_TIPODOCUMENTO)
VALUES 
(1, 'Cédula de Ciudadanía', 'A'),
(2, 'Tarjeta de Identidad', 'A'),
(3, 'Cédula de Extranjería', 'A'),
(4, 'Pasaporte', 'A');


INSERT INTO TIPOCLIENTE (ID_TIPOCLIENTE, DESCRIPCION_TIPOCLIENTE, ESTADO_TIPOCLIENTE)
VALUES 
(1, 'Persona Natural', 'A'),
(2, 'Persona Jurídica', 'A');


INSERT INTO TIPOPROVEEDOR (ID_TIPOPROVEEDOR, NOMBRE_TIPOPROVEEDOR, ESTADO_TIPOPROVEEDOR)
VALUES 
(1, 'Proveedor de Mercancía', 'A'),
(2, 'Proveedor de Servicios Técnicos', 'A');