CREATE DATABASE CIMOVE;
\c CIMOVE;

CREATE TABLE CATEGORIA (
    ID_CATEGORIA SERIAL PRIMARY KEY,
    DESCRIPCION_CATEGORIA VARCHAR(255) NOT NULL,
    ESTADO_CATEGORIA CHAR(1) NOT NULL DEFAULT 'A'
);

CREATE TABLE PRODUCTO (
    ID_PRODUCTO SERIAL PRIMARY KEY,
    ID_CATEGORIA_PRODUCTO INT NOT NULL,
    NOMBRE_PRODUCTO VARCHAR(255) NOT NULL,
    DESCRIPCION_PRODUCTO VARCHAR(500),
    PRECIOVENTAACT_PRODUCTO INT NOT NULL,
    PRECIOVENTAANT_PRODUCTO INT,
    COSTOVENTA_PRODUCTO INT NOT NULL,
    MARGENUTILIDAD_PRODUCTO INT,
    VALORIVA_PRODUCTO DOUBLE PRECISION,
    ESTADO_PRODUCTO CHAR(1) NOT NULL DEFAULT 'A',
    CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA_PRODUCTO) REFERENCES CATEGORIA(ID_CATEGORIA)
);

CREATE TABLE INVENTARIO (
    ID_INVENTARIO SERIAL PRIMARY KEY,
    ID_PRODUCTO_INVENTARIO INT NOT NULL,
    EXISTENCIA_INVENTARIO INT NOT NULL,
    ESTADO_INVENTARIO CHAR(1) NOT NULL DEFAULT 'A',
    CONSTRAINT FK_INVENTARIO_PRODUCTO FOREIGN KEY (ID_PRODUCTO_INVENTARIO) REFERENCES PRODUCTO(ID_PRODUCTO)
);

CREATE TABLE PAIS (
    ID_PAIS VARCHAR(10) PRIMARY KEY,
    NOMBRE_PAIS VARCHAR(255) NOT NULL,
    ESTADO_PAIS CHAR(1) NOT NULL DEFAULT 'A'
);

CREATE TABLE DEPARTAMENTO (
    ID_DPTO VARCHAR(10) PRIMARY KEY,
    NOMBRE_DPTO VARCHAR(255) NOT NULL,
    ID_PAIS_DPTO VARCHAR(10) NOT NULL,
    ESTADO_DPTO CHAR(1) NOT NULL DEFAULT 'A',
    CONSTRAINT FK_DEPARTAMENTO_PAIS FOREIGN KEY (ID_PAIS_DPTO) REFERENCES PAIS(ID_PAIS)
);

CREATE TABLE CIUDAD (
    ID_CIUDAD VARCHAR(10) PRIMARY KEY,
    NOMBRE_CIUDAD VARCHAR(255) NOT NULL,
    ID_DPTO_CIUDAD VARCHAR(10) NOT NULL,
    ESTADO_CIUDAD CHAR(1) NOT NULL DEFAULT 'A',
    CONSTRAINT FK_CIUDAD_DEPARTAMENTO FOREIGN KEY (ID_DPTO_CIUDAD) REFERENCES DEPARTAMENTO(ID_DPTO)
);

CREATE TABLE SEDE (
    ID_SEDE SERIAL PRIMARY KEY,
    NOMBRE_SEDE VARCHAR(255) NOT NULL,
    ID_CIUDAD_SEDE VARCHAR(10) NOT NULL,
    DIRECCION_SEDE VARCHAR(255) NOT NULL,
    NUMEROEMPLEADOS_SEDE INT NOT NULL,
    TELEFONO_SEDE VARCHAR(20),
    ESTADO_SEDE CHAR(1) NOT NULL DEFAULT 'A',
    CONSTRAINT FK_SEDE_CIUDAD FOREIGN KEY (ID_CIUDAD_SEDE) REFERENCES CIUDAD(ID_CIUDAD)
);

CREATE TABLE INVENTARIOLOCAL (
    ID_INVENTARIOLOCAL SERIAL PRIMARY KEY,
    ID_PRODUCTO_INVENTARIOLOCAL INT NOT NULL,
    ID_SEDE_INVENTARIOLOCAL INT NOT NULL,
    EXISTENCIA_INVENTARIOLOCAL INT NOT NULL,
    STOCKMINIMO_INVENTARIOLOCAL INT,
    STOCKMAXIMO_INVENTARIOLOCAL INT NOT NULL,
    ESTADO_INVENTARIOLOCAL CHAR(1) NOT NULL DEFAULT 'A',
    CONSTRAINT FK_INVENTARIOLOCAL_PRODUCTO FOREIGN KEY (ID_PRODUCTO_INVENTARIOLOCAL) REFERENCES PRODUCTO(ID_PRODUCTO),
    CONSTRAINT FK_INVENTARIOLOCAL_SEDE FOREIGN KEY (ID_SEDE_INVENTARIOLOCAL) REFERENCES SEDE(ID_SEDE)
);

CREATE TABLE TIPOPMOV (
    ID_TIPOMOV SERIAL PRIMARY KEY,
    NOM_TIPOMOV VARCHAR(50),
    ESTADO_TIPOMOV VARCHAR(20)
);

CREATE TABLE MOVPRODUCTO (
    ID_MOV SERIAL PRIMARY KEY,
    ID_TIPOMOV INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CANTIDAD_MOV INT,
    FECHA_MOVIMIENTO DATE,
    ESTADO_MOVIMIENTO VARCHAR(20),
    CONSTRAINT fk_tipomov_producto FOREIGN KEY (ID_TIPOMOV) REFERENCES TIPOPMOV (ID_TIPOMOV),
    CONSTRAINT fk_producto_movimiento FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
);



INSERT INTO PAIS (ID_PAIS, NOMBRE_PAIS, ESTADO_PAIS) VALUES ('COL', 'Colombia', 'A');


INSERT INTO DEPARTAMENTO (ID_DPTO, NOMBRE_DPTO, ID_PAIS_DPTO) VALUES ('25', 'Cundinamarca', 'COL');

INSERT INTO DEPARTAMENTO (ID_DPTO, NOMBRE_DPTO, ID_PAIS_DPTO) VALUES ('11', 'Bogotá D.C.', 'COL');


INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_DPTO_CIUDAD) VALUES ('11.001', 'Bogotá', '11');

INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_DPTO_CIUDAD) VALUES ('25.126', 'Cajicá', '25');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_DPTO_CIUDAD) VALUES ('25.214', 'Cota', '25');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_DPTO_CIUDAD) VALUES ('25.286', 'Funza', '25');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_DPTO_CIUDAD) VALUES ('25.377', 'La Calera', '25');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_DPTO_CIUDAD) VALUES ('25.43', 'Madrid', '25');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_DPTO_CIUDAD) VALUES ('25.473', 'Mosquera', '25');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_DPTO_CIUDAD) VALUES ('25.754', 'Soacha', '25');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_DPTO_CIUDAD) VALUES ('25.785', 'Tabio', '25');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_DPTO_CIUDAD) VALUES ('25.799', 'Tenjo', '25');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_DPTO_CIUDAD) VALUES ('25.899', 'Zipaquirá', '25');
